### ISSUE TITLE
Naprawa łączeń linoleum

### ISSUE THREAD

**Issue by twiniars** [RCPRG-ros-pkg/RicoMechanics#3]
Jak się okaże, że nowe sprężyny gazowe nie pomogą, to trzeba wymienić listwy. Wygląda jednak na to, że trzeba tylko uzupełnić te, które uległy uszkodzeniu

**Comment by Dangield** [comment]
[GAH Alberts Profil podłogowy aluminiowy 38 mm x 900 mm](https://www.obi.pl/profile/gah-alberts-profil-podlogowy-aluminiowy-38-mm-x-900-mm/p/3380235)
[GAH Alberts Profil podłogowy aluminiowy 38 mm x 2000 mm](https://www.obi.pl/profile/gah-alberts-profil-podlogowy-aluminiowy-38-mm-x-2000-mm/p/3380201)

**Comment by Dangield** [comment]
Nieaktualne po wymianie sprężyn gazowych w podwoziu.
